project_id = "mnixswaiifzqjydhxhuk"

[functions.get-trial-key]
verify_jwt = false

[functions.fetch-telegram-post]
verify_jwt = false

[functions.play-game]
verify_jwt = false

[functions.track-visit]
verify_jwt = false